/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-11-02 14:42:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class patientreceiving_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>patient</title>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction AlertMessage(result)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(result==0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"UID does not accept zero value\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==5)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"UID does not accept negative numbers\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (result==2)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"UID cannot be more than 9999999999\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\" uid data is not filled in required fields\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==4)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t \talert(\"UID accepts only numbers\");\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==6)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"firstname data is not filled in required fields\");\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==7)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"firstname does not accept numbers & special characters other than space\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==8)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Length of the firstname cannot be more than 50 characters\");\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==9)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"lastname data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==10)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"lastname does not accept numbers & special characters other than space\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==11)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Length of the lastname cannot be more than 50 characters\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==12)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==13)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age accepts only numbers\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==14)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age does not accept negative numbers\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==15)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age does not accept zero value\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==16)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age cannot be more than 150\")\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"AlertMessage(");
      out.print( session.getAttribute("valid") );
      out.write(")\">\r\n");
      out.write("<form>\r\n");
      out.write("\t");

		String uid1=request.getParameter("uid");
		String firstname1=request.getParameter("firstname");
		String lastname1=request.getParameter("lastname");
		String age1=request.getParameter("age");
		String gender1=request.getParameter("gender");
		String dob1=request.getParameter("dob");
		String height1=request.getParameter("height");
		String weight1=request.getParameter("weight");
		String birthday1=request.getParameter("birthday");
		String address1=request.getParameter("address");
		String aadhaarno1=request.getParameter("aadhaarno");
		String mobilenumber1=request.getParameter("mobilenumber");
		String mailid1=request.getParameter("mailid");
		String studytype1=request.getParameter("studytype");
		
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("UID:<br><input type=\"text\" name=\"UID\" value=");
      out.print(uid1 );
      out.write(">\r\n");
      out.write("<br><br>\r\n");
      out.write("FirstName:<br><input type=\"text\" name=\"firstname\" value=");
      out.print(firstname1 );
      out.write(" >\r\n");
      out.write("  <br><br>\r\n");
      out.write("LastName:<br><input type=\"text\" name=\"lastname\" value=");
      out.print(lastname1 );
      out.write(" >\r\n");
      out.write("  <br><br>\r\n");
      out.write("Age:<br><input type=\"text\" name=\"age\" value=");
      out.print(age1 );
      out.write(">\r\n");
      out.write("<br><br>\r\n");
      out.write("Gender:<br><select name=\"gender\"  value=");
      out.print(gender1 );
      out.write(">\r\n");
      out.write("  <option value=\"Male\">Male</options>\r\n");
      out.write("  <option value=\"Female\">Female</option>\r\n");
      out.write("  <option value=\"Others\">Others</option>\r\n");
      out.write("  </select>\r\n");
      out.write("  <br><br>\r\n");
      out.write("DOB:<br><input type=\"text\" name=\"dob\" value=");
      out.print(dob1);
      out.write(">\r\n");
      out.write("<br><br>\r\n");
      out.write("Height:<br><input type=\"text\" name=\"height\" value=");
      out.print(height1 );
      out.write(">\r\n");
      out.write("<br><br>\r\n");
      out.write("Weight:<br><input type=\"text\" name=\"weight\" value=");
      out.print(weight1 );
      out.write(">\r\n");
      out.write("<br><br>\r\n");
      out.write("BirthDay:<br><input type=\"text\" name=\"birthday\" value=");
      out.print(birthday1 );
      out.write(">\r\n");
      out.write("<br><br>\r\n");
      out.write("Address:<br><input type=\"text\" name=\"address\" value=");
      out.print(address1 );
      out.write(">\r\n");
      out.write("<br><br>\r\n");
      out.write("AadhaarNo:<br> <input type=\"text\" name=\"aadhaarno\" value=");
      out.print(aadhaarno1 );
      out.write(">\r\n");
      out.write("<br><br>\r\n");
      out.write("MobileNumber:<br><input type=\"text\" name=\"mobilenumber\" value=");
      out.print(mobilenumber1 );
      out.write(">\r\n");
      out.write("  <br><br>\r\n");
      out.write("MailId:<br><input type=\"text\" name=\"mailid\" value=");
      out.print(mailid1 );
      out.write(">\r\n");
      out.write("  <br><br>\r\n");
      out.write("Study Type:<br><select name=studytype value=");
      out.print(studytype1 );
      out.write(">\r\n");
      out.write("  <option value=\"Coronary\">Coronary</options>\r\n");
      out.write("  <option value=\"Pediatric\">Pediatric</option>\r\n");
      out.write("  <option value=\"ElectroPhysiology\">ElectroPhysiology</option>\r\n");
      out.write(" </select>\r\n");
      out.write(" <br><br> \r\n");
      out.write("  <input type=\"submit\" value=\"Register\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
