/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-11-16 16:13:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class patientdata_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>patient</title>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction AlertMessage(result)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ta=1;\r\n");
      out.write("\t\t\tb=2;\r\n");
      out.write("\t\t\tc=a+b;\r\n");
      out.write("\t\t\talert(\"Test\" + c);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(result==0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"UID does not accept zero value\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==5)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"UID does not accept negative numbers\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (result==2)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"UID cannot be more than 9999999999\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\" uid data is not filled in required fields\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==4)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t \talert(\"UID accepts only numbers\");\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==6)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"firstname data is not filled in required fields\");\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==7)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"firstname does not accept numbers & special characters other than space\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==8)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Length of the firstname cannot be more than 50 characters\");\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==9)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"lastname data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==10)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"lastname does not accept numbers & special characters other than space\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==11)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Length of the lastname cannot be more than 50 characters\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==12)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==13)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age accepts only numbers\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==14)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age does not accept negative numbers\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==15)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age does not accept zero value\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==16)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"age cannot be more than 150\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==17)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Gender cannot be given other than Male, Female and Other\")\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==18)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"dob data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==19)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"In dob year should not be less than 1866\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==20)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Height data is not correct format\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==21)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Weight data is not filled in required fields\")\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==22)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Weight does not accept negative numbers\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==23)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Weight does not accept more than 300\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==24)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Birthday data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==25)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Birthday does not accept numbers & special characters\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==26)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Length of the birthday cannot be more than 50 characters\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==27)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Address data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==28)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Address does not accept any special characters other than #, .(dot) and @\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==29)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Aadhaarno data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==30)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Aadhaarno accepts only numbers\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==31)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Aadhaarno does not accept more than 16digits\")\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==32)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"MobileNumber data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==33)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"MobileNumber accepts only numbers \");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==34)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"MobileNumber does not accept more than 10digits\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==35)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Mailid data is not filled in required fields\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==36)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Given mailid is not in correct format\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==37)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Studytype cannot be given other than Coronary,Pediatric and Electrophysiology\");\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==38)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"registered succesfully\")\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(result==39)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Given uid value already exists\")\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:yellow;\" onload=\"AlertMessage(");
      out.print( session.getAttribute("valid") );
      out.write(")\">\r\n");
      out.write("<h1 style=\"color:blue;font-size:300%;text-align:center;\"> Welcome to Patient Registration </h1>\r\n");
      out.write("<p style=\"text-align:left;\"> Information is about the website , it was found in 2016 and purpose of www.patient.com is to sign-in and fix the doctors appointment ,is a framework to link various hospitals across the country for Aadhaar based online registration and appointment system, where counter based OPD registration and appointment system through Hospital Management Information System (HMIS) has been digitalized. The application has been hosted on the cloud services of NIC. Portal facilitates online appointments with various departments of different Hospitals using eKYC data of Aadhaar number, if patient's mobile number is registered with UIDAI. And in case mobile number is not registered with UIDAI it uses patient's name. New Patient will get appointment as well as Unique Health Identification (UHID) number. If Aadhaar number is already linked with UHID number, then appointment number will be given and UHID will remain same.</p>\r\n");
      out.write("<br><br>\r\n");
      out.write("<a href=\"\">Doctors Appointment</a>\r\n");
      out.write("<a href=\"\">Contact Us</a>\r\n");
      out.write("<a href=\"\">Services</a>\r\n");
      out.write("<a href=\"\">Feedback</a>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("<a href=\"\">Sign-In/Register</a>\r\n");
      out.write("<br><br>\r\n");
      out.write("<form action=\"patientservlet\" method=\"post\">\r\n");
      out.write("UID:<br><input type=\"text\" name=\"uid\" value=1>\r\n");
      out.write("<br><br>\r\n");
      out.write("FirstName:<br><input type=\"text\" name=\"firstname\" value=\"tulasi\">\r\n");
      out.write("  <br><br>\r\n");
      out.write("LastName:<br><input type=\"text\" name=\"lastname\" value=P>\r\n");
      out.write("  <br><br>\r\n");
      out.write("Age:<br><input type=\"text\" name=\"age\" value=31>\r\n");
      out.write("<br><br>\r\n");
      out.write("Gender:<br><select name=\"gender\"> \r\n");
      out.write("  <option value=\"Male\">Male</options>\r\n");
      out.write("  <option value=\"Female\">Female</option>\r\n");
      out.write("  <option value=\"Others\">Others</option>\r\n");
      out.write("  <option value=\"\"></options>\r\n");
      out.write("  </select>\r\n");
      out.write("  <br><br>\r\n");
      out.write("DOB:<br><input type=\"text\" name=\"dob\" value=12/09/2011>\r\n");
      out.write("<br><br>\r\n");
      out.write("Height:<br><input type=\"text\" name=\"height\" value= \"5' 6\"\" >\r\n");
      out.write("<br><br>\r\n");
      out.write("Weight:<br><input type=\"text\" name=\"weight\" value=75>\r\n");
      out.write("<br><br>\r\n");
      out.write("BirthDay:<br><input type=\"text\" name=\"birthday\" value=sunday>\r\n");
      out.write("<br><br>\r\n");
      out.write("Address:<br><input type=\"text\" name=\"address\" value=bhjdshuihj>\r\n");
      out.write("<br><br>\r\n");
      out.write("AadhaarNo:<br> <input type=\"text\" name=\"aadhaarno\" value=645786937>\r\n");
      out.write("<br><br>\r\n");
      out.write("MobileNumber:<br><input type=\"text\" name=\"mobilenumber\" value=65784897>\r\n");
      out.write("  <br><br>\r\n");
      out.write("MailId:<br><input type=\"text\" name=\"mailid\" value=gydufgu@yahoo.com>\r\n");
      out.write("  <br><br>\r\n");
      out.write("Study Type:<br>\r\n");
      out.write("<select name=studytype>\r\n");
      out.write("\t<option></options>\r\n");
      out.write("\t<option>Coronary</options>\r\n");
      out.write("\t<option>Pediatric</option>\r\n");
      out.write("\t<option>ElectroPhysiology</option> \r\n");
      out.write("</select>\r\n");
      out.write(" <br><br> \r\n");
      out.write("  <input type=\"submit\" value=\"Register\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
